### ISSUE TITLE
(Request) Healthcheck or ability to support healthchecks

### ISSUE THREAD

**Issue by michael1800v1** [bluegoosemedia/atmoify#2]
Please consider implementing a simple internal healthcheck or at least adjusting the configuration to allow for healthchecks specified from the compose file. The checks are used by Docker Compose, Swarm and K8 deployments to make sure the service is up, restart on failures and move between nodes for maintenance, hardware failures, backups, etc. as well as automatically spinning up and scaling to 0 containers (on-demand).

The current container already includes wget, however, node only binds to the docker-provided IP and hostname (as 'local'?), neither of which are predictable in most Swarm/K8 environments. While setting the hostname and internal IP can be done, this is generally a very bad move.

Unfortunately, I am not a node.js guy, so I don't know what the best answer is here. I haven't had this problem with other node-based projects; usually, node is listening on 127.0.0.1[:port], but isn't in this case.

This low priority, but is extremely helpful for many users and would absolutely be appreciated.

**Comment by bluegoosemedia** [comment]
I have created a beta docker image that you can try out and see if it resolves your problem. 

I am no expert in this and I have never used any K8/Swarm stuff, so I don't really have the knowledge to test it. 

I think it should work, but please verify and let me know. 

Here is an updated docker-compose.yml example file. 

`version: '3.9'

services:
  app:
    image: ghcr.io/bluegoosemedia/atmoify:beta
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
`

**Comment by bluegoosemedia** [comment]
I have created a beta docker image that you can try out and see if it resolves your problem.

I am no expert in this and I have never used any K8/Swarm stuff, so I don't really have the knowledge to test it.

I think it should work, but please verify and let me know.

Here is an updated docker-compose.yml example file.

```
version: '3.9'

services:
  app:
    image: ghcr.io/bluegoosemedia/atmoify:beta
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

```
